"""Generate frontend request contracts from the authoritative Pydantic schemas."""

import argparse
import json
from pathlib import Path

from src.app.api.v4_routes import ApplyChoice, Outcome, ScenarioChoice, ScheduleSettings
from src.app.domain.contracts import AnalysisRequest

MODELS = (AnalysisRequest, ScenarioChoice, ApplyChoice, Outcome, ScheduleSettings)
TARGET = Path(__file__).resolve().parents[2] / "frontend/src/lib/generated/api-contracts.ts"


def typescript(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(typescript(part) for part in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{typescript(schema.get('items', {}))}>"
    if kind == "object":
        required = schema.get("required", [])
        fields = [
            f"  {json.dumps(name)}{'' if name in required else '?'}: {typescript(value)};"
            for name, value in schema.get("properties", {}).items()
        ]
        return "{\n" + "\n".join(fields) + "\n}"
    return {
        "string": "string",
        "number": "number",
        "integer": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def render() -> str:
    definitions = {}
    declarations = []
    for model in MODELS:
        schema = model.model_json_schema(by_alias=True)
        definitions.update(schema.get("$defs", {}))
        declarations.append(f"export type {model.__name__} = {typescript(schema)};")
    aliases = [
        f"export type {name} = {typescript(schema)};" for name, schema in definitions.items()
    ]
    return (
        "// Generated by apps/api/scripts/export_api_contracts.py. Do not edit.\n\n"
        + "\n\n".join(aliases + declarations)
        + "\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != expected:
            raise SystemExit("API request contracts are stale; run scripts/export_api_contracts.py")
    else:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(expected)
